### PR TITLE
Always use the latest stable Rust version on Travis

### PR DESCRIPTION
**Pull request by rushmorem**

### CODE REVIEW

**Comment by sfackler** [comment]
We're pinning to that version intentionally to make sure we're aware when we drop support for that version of Rust. The nightly and beta tests should handle tests against more modern versions.

**Comment by rushmorem** [comment]
Ah, I see...

**Comment by sfackler** [comment]
I realized it's probably best to have a consistent snapshot of both values so I modified this just a bit. Publishing now: https://github.com/sfackler/r2d2/commit/731b389a05b90e235de3dcd6cd155853fd062b10

**Comment by rushmorem** [comment]
Indeed, having a consistent snapshot is the best way to go. Thanks! Just curious though, what is the purpose of the [_p]?

[_p]: https://github.com/sfackler/r2d2/blob/731b389a05b90e235de3dcd6cd155853fd062b10/src/lib.rs#L485

**Comment by sfackler** [comment]
We can make all of the other fields public. The private field allows us to add new public fields in the future without breaking backwards compatibility.

**Comment by rushmorem** [comment]
Neat! I didn't know this trick. I'm glad I asked :)

**Pull request closed without merging**
